In [ ]:
# 2. Part 2 â€“ TEXT MINING.
# 2.1. Text mining is the process of analyzing collections of textual materials in order to 
# capture key concepts and themes and uncover hidden relationships and trends 
# without requiring that you know the precise words or terms that authors have used 
# to express those concepts.
# 2.2. To make sense of the text and make it useful for various ML techniques, there has 
# to be a numeric way to express the text.
# 2.3. Your task is to create a count vector and a tfidf vector on the given data (refer to 2. 
# In the resources below).
# 2.4. Display the count vector and tfidf vector and explain the usage of tfidf.


# data for data minig from resources page section 4.2

from pandas import DataFrame 
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

data = [ 'Now for manners use has company believe parlors.',
'Least nor party who wrote while did. Excuse formed as is agreed admire so on result parish.',
'Put use set uncommonly announcing and travelling. Allowance sweetness direction to as necessary.',
'Principle oh explained excellent do my suspected conveying in.',
'Excellent you did therefore perfectly supposing described. ',
'Its had resolving otherwise she contented therefore.',
'Afford relied warmth out sir hearts sister use garden.',
'Men day warmth formed admire former simple.',
'Humanity declared vicinity continue supplied no an. He hastened am no property exercise of. ' ,
'Dissimilar comparison no terminated devonshire no literature on. Say most yet head room such just easy. ']

In [ ]:
def create_document_matrix(listofmessages,vectorizer):
    doc_tr_matrix = vectorizer.fit_transform(listofmessages)
    return DataFrame(doc_tr_matrix.toarray(),columns = vectorizer.get_feature_names_out())

In [ ]:
count_vector = CountVectorizer()

In [ ]:
#count vector
create_document_matrix(data,count_vector)

,admire,afford,agreed,allowance,am,an,and,announcing,as,believe,...,travelling,uncommonly,use,vicinity,warmth,while,who,wrote,yet,you
0,0,0,0,0,0,0,0,0,0,1,...,0,0,1,0,0,0,0,0,0,0
1,1,0,1,0,0,0,0,0,1,0,...,0,0,0,0,0,1,1,1,0,0
2,0,0,0,1,0,0,1,1,1,0,...,1,1,1,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,1,0,0,0,0,0,0,0,0,...,0,0,1,0,1,0,0,0,0,0
7,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
8,0,0,0,0,1,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [ ]:
#TF-IDF

#TF means term frequency 

tfidf_vector = TfidfVectorizer()

create_document_matrix(data, tfidf_vector)

,admire,afford,agreed,allowance,am,an,and,announcing,as,believe,...,travelling,uncommonly,use,vicinity,warmth,while,who,wrote,yet,you
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.363862,...,0.000000,0.000000,0.270615,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.215139,0.000000,0.253077,0.000000,0.000000,0.000000,0.000000,0.000000,0.215139,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.253077,0.253077,0.253077,0.000000,0.000000
2,0.000000,0.000000,0.000000,0.285414,0.000000,0.000000,0.285414,0.285414,0.242628,0.000000,...,0.285414,0.285414,0.212271,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.402651
5,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6,0.000000,0.347612,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.258530,0.000000,0.295502,0.000000,0.000000,0.000000,0.000000,0.000000
7,0.342290,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.342290,0.000000,0.000000,0.000000,0.000000,0.000000
8,0.000000,0.000000,0.000000,0.000000,0.259145,0.259145,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.259145,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.245342,0.000000

In [ ]:
# the usege of TFIDF
# Vectorization is nothing but converting text into numeric form.
# As we know regardless of how much machines are capable and powerful,
# still they do not understand words and sentences as same manner as humans do,
# so to make that possible for machines to understand texts first we need to convert
# them  to a numerical representation.